-- Insert data into university_table
INSERT INTO university_table (uni_id, real_name) VALUES
    ('d87b6c4a', 'Driedcat University'),
    ('e75a0d63', 'Sloppydog University'),
    ('f29c1e8b', 'Brightfish College'),
    ('g3b1f2d4', 'Whisperingtree Institute'),
    ('h4e5d6b8', 'Gentlepenguin School'),
    ('i5g7h8j9', 'Starryowl University'),
    ('j6k8l9m1', 'Silenttiger College'),
    ('k7n9o1p2', 'Blazinghorse Institute'),
    ('l8q9r1s2', 'Freezewolf University'),
    ('m9t1u2v3', 'Goldenfrog College'),
    ('n1o2p3q4', 'Rapidhawk School'),
    ('o2r3s4t5', 'Thundermonkey University'),
    ('p3u4v5w6', 'Fireswan College'),
    ('q4w5e6r7', 'Cleverfox Institute'),
    ('r5t6y7u8', 'Swiftdeer University'),
    ('s6u7i8t9', 'Majesticbear College'),
    ('t7u8v9w1', 'Cunningbadger School'),
    ('u8w9x1y2', 'Glowingelephant Institute'),
    ('v9x1y2z3', 'Mysticlion University'),
    ('w1x2y3z4', 'Wanderingkoala College'),
    ('x2y3z4a5', 'Crimsonkangaroo School'),
    ('y3z4a5b6', 'Howlingdolphin University'),
    ('z4a5b6c7', 'Lunarbat College'),
    ('a5b6c7d8', 'Sizzlingcheetah Institute'),
    ('b6c7d8e9', 'Dancingwhale University'),
    ('c7d8e9f1', 'Sparklingseagull College'),
    ('d8e9f1g2', 'Spiritedgiraffe School'),
    ('e9f1g2h3', 'Tranquilrhino University'),
    ('f1g2h3i4', 'Vibrantlemur College');

-- Insert data into synonym_table
INSERT INTO synonym_table (synonym_text, language) VALUES
    ('Dried Cat University', 'English'),
    ('Dry Cat University', 'English'),
    ('Sloop Dough University', 'English'),
    ('Bright Fish College', 'English'),
    ('Whispering Tree Institute', 'English'),
    ('Gentle Penguin School', 'English'),
    ('Starry Owl University', 'English'),
    ('Silent Tiger College', 'English'),
    ('Blazing Horse Institute', 'English'),
    ('Freeze Wolf University', 'English'),
    ('Golden Frog College', 'English'),
    ('Rapid Hawk School', 'English'),
    ('Thunder Monkey University', 'English'),
    ('Fire Swan College', 'English'),
    ('Clever Fox Institute', 'English'),
    ('Swift Deer University', 'English'),
    ('Majestic Bear College', 'English'),
    ('Cunning Badger School', 'English'),
    ('Glowing Elephant Institute', 'English'),
    ('Mystic Lion University', 'English'),
    ('Wandering Koala College', 'English'),
    ('Crimson Kangaroo School', 'English'),
    ('Howling Dolphin University', 'English'),
    ('Lunar Bat College', 'English'),
    ('Sizzling Cheetah Institute', 'English'),
    ('Dancing Whale University', 'English'),
    ('Sparkling Seagull College', 'English'),
    ('Spirited Giraffe School', 'English'),
    ('Tranquil Rhino University', 'English'),
    ('Vibrant Lemur College', 'English');

